# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

################################################################################
#
#    Arma Router Configuration Template
#
################################################################################

# PartyID a unique identifier for each Arma party, uint16, id>0
PartyID: 1

################################################################################
#
#   SECTION: General: same as in template
#
################################################################################
General:

################################################################################
#
#   SECTION: File Store: same as in template
#
################################################################################
FileStore:

################################################################################
#
#   SECTION: Role specific configuration: only `Router` key
#
################################################################################

# Router specific parameters
Router:
  NumberOfConnectionsPerBatcher: 10
  NumberOfStreamsPerConnection: 20
