# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

PartyID: 4
General:
    ListenAddress: 127.0.0.1
    ListenPort: 60625
    TLS:
        Enabled: true
        PrivateKey: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/batcher1/tls/key.pem
        Certificate: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/batcher1/tls/tls-cert.pem
        RootCAs:
            - /var/dec-trust/crypto/ordererOrganizations/org4/tlsca/tlsca-cert.pem
        ClientAuthRequired: false
    Keepalive:
        ClientInterval: 1m0s
        ClientTimeout: 20s
        ServerInterval: 2h0m0s
        ServerTimeout: 20s
        ServerMinInterval: 1m0s
    Backoff:
        BaseDelay: 1s
        Multiplier: 1.6
        MaxDelay: 2m0s
    MaxRecvMsgSize: 104857600
    MaxSendMsgSize: 104857600
    Bootstrap:
        Method: block
        File: /var/dec-trust/bootstrap/bootstrap.block
    LocalMSPDir: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/batcher1/msp
    LocalMSPID: OrdererOrg4
    BCCSP:
        Default: SW
        SW:
            Hash: SHA2
            Security: 256
            FileKeyStore:
                KeyStore:
    LogSpec: info
    ClientSignatureVerificationRequired: false
    MetricsLogInterval: 0s
FileStore:
    Location: /var/dec-trust/production/orderer/store
Batcher:
    ShardID: 1
    BatchSequenceGap: 10
    MemPoolMaxSize: 1000000
    SubmitTimeout: 500ms
